HW1 is completed
IslamovZ/Otus pull request #1
Opened 2022-06-06 13:36 UTC by IslamovZ

## Домашнее задание №1 «Hello, OTUS!»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я использовал `stringutil.Reverse`.
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~12 строк

### Критерии оценки
- [x] Пайплайн зелёный - 4 балла
- [x] Используется `stringutil` - 4 балла
- [x] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-07 10:31 UTC, egakupi requested changes
Спасибо за выполнение домашнего задания. Осталось поправить go.mod.

Если будут вопросы – пишите

2022-06-07 10:31 UTC, egakupi commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
Проверьте, будет ли работать go get для данного модуля

2022-06-07 10:31 UTC, egakupi commented on hw01_hello_otus/main.go
> +const stringForReverse = "Hello, OTUS!"
Увидел, что балуетесь с синтаксисом. 
Вне контекста первой домашки подобный код – усложнение.

2022-06-09 19:45 UTC, IslamovZ commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
исправил адрес - теперь работает)

2022-06-09 19:47 UTC, IslamovZ commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
все таки адрес модуля должен совпадать с репой (или папкой в репе) - этого не понял

2022-06-10 12:56 UTC, egakupi requested changes

2022-06-10 12:56 UTC, egakupi commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
Достаточно будет github.com/IslamovZ/Otus/hw01_hello_otus
Для указывания какой-то конкретной версии используются теги. Если интересно – можно почитать: https://go.dev/blog/publishing-go-modules

2022-06-13 07:17 UTC, IslamovZ commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
После того как убрал tree/master из адреса при попытке взять модуль выдает следующее 
go get github.com/IslamovZ/Otus/hw01_hello_otus       
parsing go.mod:
        module declares its path as: github.com/fixme_my_friend/hw01_hello_otus
                but was required as: github.com/IslamovZ/Otus/hw01_hello_otus

как это поправить?

2022-06-13 07:18 UTC, IslamovZ commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
а еще если попытаться перейти по github.com/IslamovZ/Otus/hw01_hello_otus в браузере тот выдает 404 - это нормально?

2022-06-14 09:27 UTC, egakupi commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
Закешировалась версия, которая `hw01_hello_otus v0.0.0-20220605141338-416e56d8ebc8`. Это можно видеть из вывода команды `go get`.

```
$ go get github.com/IslamovZ/Otus/hw01_hello_otus
go: downloading github.com/IslamovZ/Otus/hw01_hello_otus v0.0.0-20220605141338-416e56d8ebc8
go: downloading github.com/IslamovZ/Otus v0.1.0
go get: github.com/IslamovZ/Otus/hw01_hello_otus@none updating to
        github.com/IslamovZ/Otus/hw01_hello_otus@v0.0.0-20220605141338-416e56d8ebc8: parsing go.mod:
        module declares its path as: github.com/fixme_my_friend/hw01_hello_otus
                but was required as: github.com/IslamovZ/Otus/hw01_hello_otus
```

Нужно немного подождать пока гитхаб обновит кеши. Проверить, что всё хорошо,  можно коммитом с последним исправлением:
` go get github.com/IslamovZ/Otus/hw01_hello_otus@256be8177173a0a6c78c378df7d3efc11180d283`

По поводу перехода в браузере – это нормально. Это строка валидна для `go get`

2022-06-14 09:31 UTC, egakupi commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
Также можете попробовать `go clean -modcache` вызвать.

Подробнее почитать – `go help clean`

The -modcache flag causes clean to remove the entire module
download cache, including unpacked source code of versioned
dependencies.

2022-06-14 09:31 UTC, egakupi approved these changes
Домашнее задание принято – 10/10

Если будут еще вопросы – пишите.
Успехов дальше!

2022-06-14 11:41 UTC, IslamovZ commented on hw01_hello_otus/go.mod
> -module github.com/fixme_my_friend/hw01_hello_otus
спасибо!

2022-07-10 12:08 UTC, merged